[build]
  # Build command para Next.js
  command = "npm run build"
  # Output directory para Next.js
  publish = "out"

# Configuración para Next.js export estático
[build.environment]
  NODE_VERSION = "18"
  # Configuración para excluir NODE_ENV del escaneo de secretos
  SECRETS_SCAN_OMIT_KEYS = "NODE_ENV"
  # Excluir directorios de build y cache del escaneo de secretos
  SECRETS_SCAN_OMIT_PATHS = ".next/**,.next/cache/**,out/**,node_modules/**,*.md"

# Redirects para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Configuración de funciones serverless
[functions]
  # Directorio donde están las funciones
  directory = "netlify/functions"
  # Runtime de Node.js
  node_bundler = "esbuild"

# Headers para CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Configuración específica para Next.js estático
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true